### ISSUE TITLE
Add a "remove Proguard library" task

### ISSUE THREAD

**Issue by krschultz** [hotchemi/gradle-proguard-plugin#2]
I was testing this out and ran into a few issues. I think the first step to improving it would be to add a remove library feature. This way we can have a complete cycle of add/remove for testing. 

Also, removing libraries was one of the primary use cases when I thought of structuring my proguard config per library. If you don't pay attention, it's easy to have a bunch of extra proguard rules that are no longer applicable for your application.

**Comment by hotchemi** [comment]
Thanks for your proposal, and it sounds good!
Do you have any idea of i/F?
